### PR TITLE
Add The Sims 3

### PR DESCRIPTION
**Pull request by Zemogiter**
Ready for review.

### CODE REVIEW

**Comment by plata** [comment]
Not sure if this is the error but there should be a `();` after `wine.vcrun2010` in the Steam script.

**Comment by plata** [comment]
Strange. But the other verbs are working if you comment the `dotnet40` line?

**Comment by Zemogiter** [comment]
Yes.

**Comment by plata** [comment]
So there must be some difference between the verbs. I tried to find something but no success.

**Comment by Zemogiter** [comment]
I've discovered there might be a problem with `dotnet35` because nothing happens when clicking the play button. But once I've installed `dotnet45` via winetricks the game works. So I've changed dotnet version but now I'm getting this error:
```
java.lang.IllegalArgumentException: Error while parsing the registry
	at org.phoenicis.win32/org.phoenicis.win32.registry.RegistryParser.parseFile(RegistryParser.java:77)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1584$1109A$\^eval\_$cu1$restOf.regedit#fetchValue([engines, wine, plugins, regedit]:52)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1582$432AA$\^eval\_.windowsVersion([engines, wine, plugins, windows_version]:15)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1581$511$\^eval\_$cu1$restOf.dotnet45([engines, wine, verbs, dotnet45]:20)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1574$812AA$\^eval\_.run#L:22(<eval>:23)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1494$553$\^eval\_$cu1$restOf.go([engines, wine, quick_script, installer_script]:75)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1463$402$\^eval\_.run(<eval>:13)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1462$\^eval\_$cu1$restOf.:program(<eval>:35)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts/org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts/org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.FileNotFoundException: /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 3/user.reg (Nie ma takiego pliku ani katalogu)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileReader.<init>(FileReader.java:75)
	at org.phoenicis.win32/org.phoenicis.win32.registry.RegistryParser.parseFile(RegistryParser.java:44)
	... 22 more
```

**Comment by plata** [comment]
Does the `user.reg` file exist?

**Comment by Zemogiter** [comment]
Yes, despite the error saying otherwise.
[user.reg.zip](https://github.com/PhoenicisOrg/scripts/files/2654132/user.reg.zip)

**Comment by Zemogiter** [comment]
The same error happens when I tested with Anno 2070 script (that game dosen't need it just for testing).

**Comment by plata** [comment]
Ok. Can you open a new issue regarding the .NET 4.5 issue?

**Comment by Zemogiter** [comment]
After some testing I concluded that even with dotnet45 installed via winetricks the game displays a rundl32.exe error. We need dotnet20 verb.

**Pull request merged**
