### PR TITLE
Games/Steam: Update wine

### PR DESCRIPTION
**Pull request by Kreyren**
Forcing latest staging since it's using 4.0 by default.

### CODE REVIEW

**Comment by Kreyren** [comment]
Results in
image

**Comment by plata** [comment]
What's the purpose of this change?

**Comment by Kreyren** [comment]
@plata Update wine for steam script assuming that it's using WINE 4.0.

**Comment by plata** [comment]
I see that but why? In general, upstream should be preferred to staging.

**Comment by Kreyren** [comment]
@plata

>  In general, upstream should be preferred to staging.

Based on what? Making something work on upstream is usually a miracle..

**Comment by qparis** [comment]
> @plata
> 
> > In general, upstream should be preferred to staging.
> 
> Based on what? Making something work on upstream is usually a miracle..

Based on what? You should be more careful before claiming such assumptions. Wine is a perfectly stable software, and I agree with @plata. Staging is experimental and should be avoided when stable releases work.

**Comment by Kreyren** [comment]
@qparis thats why i said usually a miracle.. fair enough then, closing.

**Pull request closed without merging**
