### PR TITLE
Update The Witcher 3: Wild Hunt, replaced GLSL with DXVK

### PR DESCRIPTION
**Pull request by Zemogiter**
After some testing I've concluded the framerate is better with vulkan while not suffering from ocasional graphical glitches from opengl.

### CODE REVIEW

**Comment by plata** [comment]
This implies that some users might not be able to use the script anymore, right? I'm just thinking if it makes sense to provide both options.

**Comment by ImperatorS79** [comment]
Note that all modern computer should have vulkan. Maybe a command to check if the computer has vulkan support can be useful. However, that implies the user has installed the driver (which is not necessary the case).

**Comment by ImperatorS79** [comment]
It's possible, but generally GPU which does not have vulkan support will give bad performance. You can also ask the user if he wants to install dxvk (a way to revert it later could be interesting in this case).

**Comment by ImperatorS79** [comment]
It's possible, but generally GPU which does not have vulkan support will give bad performance. You can also ask the user if he wants to install dxvk (a way to revert it later could be interesting in this case)

**Pull request merged**
