### PR TITLE
Add Assassin's Creed: Odyssey

### PR DESCRIPTION
**Pull request by Kreyren**
Credit: https://github.com/Haoose/UPLAY_GAME_ID/blob/master/README.md

Blocked by: https://github.com/PhoenicisOrg/scripts/pull/978

Blocked by: https://github.com/PhoenicisOrg/scripts/issues/881 -> Can't test!

### CODE REVIEW

**Comment by qparis** [comment]
Does the game run?

**Comment by Kreyren** [comment]
> Does the game run?

> Blocked by: #978

**Comment by plata** [comment]
Blocking pr has been merged. Is this working now?

**Comment by Kreyren** [comment]
> Blocking pr has been merged. Is this working now?

Based on available info it should, but i didn't have the opportunity to test it on phoenicis yes so either push in testing or wait for me to test.

**Comment by plata** [comment]
In this case, please state this in the pull request description set the pull request to draft. Same for other pull requests like explained before.

**Comment by Kreyren** [comment]
> In this case, please state this in the pull request description set the pull request to draft. Same for other pull requests like explained before.

*push request, stop allowing github to confuse ppl :p 

Insane, but okay

**Comment by plata** [comment]
Like explained before, we cannot accept untested pull requests. Therefore I will close this until it is tested.

**Comment by Kreyren** [comment]
Why do we have testing flag then.. w/e i will adapt for testing then..

**Comment by plata** [comment]
To quote from the [documentation](https://phoenicisorg.github.io/scripts/Develop/script-json/):

> testingOperatingSystems
Operating systems for which the script is in beta. Should be set if you are unsure that the script will run properly for everybody (like if it requires a huge amount of hack, or if it is not compatible with a any graphics cards, etc…).

**Comment by Kreyren** [comment]
@plata seems fitting for all my AC scripts

**Comment by plata** [comment]
No. You cannot even be sure that it works *at all*.

**Comment by Kreyren** [comment]
@plata because phoenicis is unable to install any steam game, adapt patches for games that depends on them like league of legends and your wine has different results compared to system wine.

if you provided system wine and resolved the quickscripts i can quarantee you that specified version of game will work.

**Pull request closed without merging**
