### PR TITLE
Udpated Star Wars Empire At War

### PR DESCRIPTION
**Pull request by ImperatorS79**
Fix missing logo

### CODE REVIEW

**Comment by madoar** [comment]
I'm not sure I see the relation between the commit and your comment "Fix missing logo"?
Did you forget to update the logo (i.e. main.png) or are you updating the name?

**Comment by ImperatorS79** [comment]
When the name in application.json and script.js differs, the logo is missing in the library tab

**Comment by madoar** [comment]
This looks like a bug to me, that the logo is missing in the library tab, if the names differ.
@plata what do you think?

**Comment by ImperatorS79** [comment]
Isn't it #269 ?

**Comment by madoar** [comment]
You're right. Seems like I forgot that we had this issue before...

**Comment by plata** [comment]
This should have been "updated" not "udpated" ;)

**Pull request merged**
