### PR TITLE
Added Dragon Ball Xenoverse 2

### PR DESCRIPTION
**Pull request by ImperatorS79**
Testing because I do not own the game.

### CODE REVIEW

**Comment by plata** [comment]
As you couldn't test the game: can you provide some evidence that it should run with that configuration (e.g. AppDB)?

**Comment by ImperatorS79** [comment]
Bronze on appDB -> [https://appdb.winehq.org/objectManager.php?sClass=version&iId=34393](https://appdb.winehq.org/objectManager.php?sClass=version&iId=34393)
But test result is odl (2.10)

**Comment by plata** [comment]
Not sure if we should merge this if all we know is an old Bronze rating.

**Comment by ImperatorS79** [comment]
It seems to work -> [https://www.youtube.com/watch?v=VGfd2z-5A6A](https://www.youtube.com/watch?v=VGfd2z-5A6A)

**Pull request merged**
