### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by plata**
Enjoy!

### CODE REVIEW

**Comment by qparis** [comment]
Can we merge this MR?

**Comment by plata** [comment]
@qparis can you finish the French translations before we merge?

**Comment by madoar** [comment]
The french script translations are completed right?

**Comment by qparis** [comment]
Mostly yes, except for some long paragraphs

**Comment by plata** [comment]
@madoar no, not fully for scripts.

@Dratui do you want to help with the scripts translations as well?

**Comment by plata** [comment]
I will merge this now so that we have at least the current state for alpha-2.

**Pull request merged**
