### PR TITLE
Fix osu!

### LINKED ISSUE #705: osu! errors out when installing
I'm confused if this is a problem with Wine, or with POL, or even with my system,
When I install osu! normally through POL5, this shows up: 
https://imgur.com/a/zr3PZxA
PB: https://pastebin.com/9BRYEnai
This happens system-wide so I am a bit confused why it doesn't work in the first place.

System: Arch x86_64

### PR DESCRIPTION
**Pull request by ImperatorS79**
Fix #705.

Depends #839.

### CODE REVIEW

**Comment by ImperatorS79** [comment]
@Zemogiter Should work now.

**Comment by ImperatorS79** [comment]
Did you delete the container before installing again ? Because I did not get this error yesterday when testing.

**Comment by Zemogiter** [comment]
I double-checked the prefix was removed and now I get this error:
```
java.lang.IllegalArgumentException: Error while parsing the registry
	at org.phoenicis.win32.registry.RegistryParser.parseFile(RegistryParser.java:77)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1044$1109A$\^eval\_$cu1$restOf.regedit#fetchValue([engines, wine, plugins, regedit]:52)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1042$432AA$\^eval\_.windowsVersion([engines, wine, plugins, windows_version]:15)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1041$408$\^eval\_$cu1$restOf.dotnet45([engines, wine, verbs, dotnet45]:17)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$994$719AA$\^eval\_.run#L:20(<eval>:23)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$914$553$\^eval\_$cu1$restOf.go([engines, wine, quick_script, installer_script]:75)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$862$305$\^eval\_.run(<eval>:11)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$861$\^eval\_$cu1$restOf.:program(<eval>:32)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.FileNotFoundException: /home/jonasz/.Phoenicis/containers/wineprefix/osu/user.reg (no such file exist)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileReader.<init>(FileReader.java:75)
	at org.phoenicis.win32.registry.RegistryParser.parseFile(RegistryParser.java:44)
	... 22 more
```
The user.reg file is present but maybe not at the exact time it is modified by dotnet installation. Once I try installing osu again (without removing prefix) I get the errors I mentioned in the last comment.

**Comment by ImperatorS79** [comment]
This seems to come from the `this.windowsVersion()` line, so it is not related to this PR. I wonder why I do not get the bug though. @plata Any idea ?

**Comment by plata** [comment]
The relevant line seems to be (from the regedit plugin):
```Javascript
var registryValue = Bean("registryParser").parseFile(new java.io.File(this.prefixDirectory() + "/" + registryFile), root).getChild(keyPath);
```

@Zemogiter can you add a check before that if the file exists?

**Comment by Zemogiter** [comment]
Like this:
```
        if ("this.prefixDirectory()/user.reg" != null)
        {
            var registryValue = Bean("registryParser").parseFile(new java.io.File(this.prefixDirectory() + "/" + registryFile), root).getChild(keyPath);
        }
```

**Comment by plata** [comment]
Should be something with `fileExists`.

**Comment by Zemogiter** [comment]
Didn't found `fileExists` but found this:
https://stackoverflow.com/questions/4482686/check-synchronously-if-file-directory-exists-in-node-js/4482701
```
        var fs = require('fs');
        if (fs.existsSync("this.prefixDirectory()/user.reg")) {
            var registryValue = Bean("registryParser").parseFile(new java.io.File(this.prefixDirectory() + "/" + registryFile), root).getChild(keyPath);
        }
```

**Comment by plata** [comment]
`fileExists` is part of the filesystem utils. If you search for it in the repository, you should find it.

**Comment by Zemogiter** [comment]
Done but now I get the same `dotnet` error as mentioned here https://github.com/PhoenicisOrg/scripts/pull/840#issuecomment-460845318

**Comment by plata** [comment]
It is just to confirm that the user.reg really does not exist at that point in time. If so, we have to figure out how this can happen.

**Comment by Zemogiter** [comment]
After downloading the latest script form #839 osu! installs and launches normally.

**Comment by qparis** [comment]
Can we merge?

**Comment by Zemogiter** [comment]
Yes.

**Pull request merged**
