### PR TITLE
Fix a "TypeError" Exception when deleting a Wine Container

### PR DESCRIPTION
**Pull request by madoar**
This PR fixes a bug when deleting a wine prefix. To be more precise it renames `get wineprefix()` to `get container()`.

This change fixes a `TypeError: <this>.runner.container is not a function` error during wine prefix deletion.

### CODE REVIEW

**Comment by ImperatorS79** [comment]
Do you also have errors when you simply click on a container (displayed in the console) ?

**Comment by madoar** [comment]
What do you mean by "clicking on a container"?

**Comment by ImperatorS79** [comment]
Click on a container in the container tab.

**Comment by madoar** [comment]
No

**Comment by ImperatorS79** [comment]
Well I got some errors due to regedit (wine settings). Will have to test on master to be sure.

**Pull request merged**
