### PR TITLE
Update Wine LATEST_DEVELOPMENT_VERSION and LATEST_STAGING_VERSION to 4.14

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by madoar** [comment]
Does `winebuild` create a fully functional (and complete) archive?
I'm asking because of https://github.com/PhoenicisOrg/phoenicis-winebuild/issues/102, https://github.com/PhoenicisOrg/scripts/pull/1076#issuecomment-520137773 and https://github.com/PhoenicisOrg/scripts/pull/1076#issuecomment-520138019

Or more precise whether these errors also occur with the new wine version?

**Comment by ImperatorS79** [comment]
No. Again if you check the log there is no space left to build the 32 bits part of wine 
https://www.playonlinux.com/wine/logs/upstream-linux-amd64/PlayOnLinux-wine-4.14-upstream-linux-amd64.log (at the end)(@qparis)

**Comment by qparis** [comment]
Should be solved

**Comment by madoar** [comment]
@ImperatorS79 can you please test again? (better safe than sorry)

**Pull request merged**
