### PR TITLE
Add Uplay option for Assassin's Creed: Revelation

### PR DESCRIPTION
**Pull request by Kreyren**
Credit: https://github.com/Haoose/UPLAY_GAME_ID/blob/master/README.md

Blocked by: https://github.com/PhoenicisOrg/scripts/pull/978

HELP_WANTED: Uplay ID is wrong

Blocked by: Blocked by https://github.com/PhoenicisOrg/scripts/issues/881 -> Can't test!

### CODE REVIEW

**Comment by Kreyren** [comment]
DO NOT MERGE

**Comment by qparis** [comment]
Does the game run?

**Comment by Kreyren** [comment]
> Does the game run?

> Blocked by: #978

**Comment by plata** [comment]
Blocking pr has been merged. Is this working now?

**Comment by Kreyren** [comment]
> Blocking pr has been merged. Is this working now?

Based on available info it should, but i didn't have the opportunity to test it on phoenicis yes so either push in testing or wait for me to test.

**Comment by plata** [comment]
Like explained before, we cannot accept untested pull requests. Therefore I will close this until it is tested.

**Pull request closed without merging**
