### PR TITLE
use ShortcutInfoDTO

### PR DESCRIPTION
**Pull request by plata**

### CODE REVIEW

**Comment by plata** [comment]
Yes, would be nice. I didn't try if it works or not.

**Comment by madoar** [comment]
We could get it working if we use the nashorn equivalent of reflection: https://docs.oracle.com/javase/8/docs/jdk/api/nashorn/jdk/nashorn/api/scripting/ScriptObjectMirror.html.
If we use this, I think we can pass json to a java method and we receive a `ScriptObjectMirror` as a parameter in the java method.

**Comment by plata** [comment]
I guess that would a bit too much effort, right?

**Comment by madoar** [comment]
I don't know. Theoretically we could add an annotation, which we can add to a DTO class.
Afterwards we can use this annotation to "automatically" convert a ScriptObjectMirror object to a DTO object.
This could be useful for all `Builder`s we're using from inside javascript.
Do you know which builders we're using from inside javascript, except the `ShortcutDTO` builder?

**Comment by plata** [comment]
No, would have to search as well. Not even sure any other builder is used.

**Pull request merged**
