### PR TITLE
Add Uplay option for Assassin's Creed III

### PR DESCRIPTION
**Pull request by Kreyren**
Credit: https://github.com/Haoose/UPLAY_GAME_ID/blob/master/README.md

~~Blocked by: https://github.com/PhoenicisOrg/scripts/pull/978~~
Blocked by #982
Blocked by https://github.com/PhoenicisOrg/scripts/issues/959
Affected by https://github.com/PhoenicisOrg/scripts/issues/881

`VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json` -> Same effect

Based on https://lutris.net/games/install/8328/view -> Corefonts and vcrun2008 are required.

Staging required https://bugs.winehq.org/show_bug.cgi?id=41181

### CODE REVIEW

**Comment by Kreyren** [comment]
There is a syntax error in 

```javascript

include("engines.wine.quick_script.uplay_script");
include("engines.wine.verbs.dxvk");

var installerImplementation = {
    run: function () {
        new UplayScript()
            .name("Assassin's Creed")
            .editor("Ubisoft, Gameloft, Ubisoft Montreal, Blue Byte, MORE")
            .applicationHomepage("https://www.ubisoft.com/en-us/game/assassins-creed")
            .author("KREYREN")
            .appId(273)
            .preInstall(function (wine/*, wizard*/) {
                wine.DXVK();
            })
            .go();
};

/* exported Installer */
var Installer = Java.extend(org.phoenicis.scripts.Installer, installerImplementation);
```

where `run: function () {` doesn't have closing argument, but Travis still succeed -> Update travis definition

**Comment by Kreyren** [comment]
ping @plata : You provided testing results on wineHQ https://appdb.winehq.org/objectManager.php?sClass=version&iId=27132&iTestingId=99347 -> Requesting info

**Comment by Kreyren** [comment]
Trying vcrun spam

**Comment by Kreyren** [comment]
> Staging required https://bugs.winehq.org/show_bug.cgi?id=41181

@qparis are all presented patches present in your staging?

**Comment by Kreyren** [comment]
image

Steam version is not working -> Push in testing asap

**Comment by plata** [comment]
I do not have any info for you except of what is written in the WineHQ entry.

**Comment by plata** [comment]
Closed due to inactivity. Feel free to reopen if the app works (according to a comment in the script, the app crashes at startup).

**Pull request closed without merging**
