### PR TITLE
Add Hitman Absolution

### PR DESCRIPTION
**Pull request by Kreyren**
Hitman Absolution script

Blocked by #930 for testing

### CODE REVIEW

**Comment by plata** [comment]
Is this finished and shall be reviewed or what's the status?

**Comment by Kreyren** [comment]
> Is this finished and shall be reviewed or what's the status?

should be merged

**Comment by plata** [comment]
Please update the PR title to match our naming guide in the README.

**Comment by Kreyren** [comment]
@plata done

**Comment by plata** [comment]
Let's see if we can fix the Steam issue first.

**Comment by Kreyren** [comment]
testrun: 
image

Configuration presented in script run locally.

**Comment by ImperatorS79** [comment]
@Kreyren So this is working ?

**Comment by Kreyren** [comment]
> @Kreyren So this is working ?

Configuration works locally on platinum, but i'm affected by https://github.com/PhoenicisOrg/phoenicis/issues/1925 which i believe is caused by https://github.com/PhoenicisOrg/scripts/issues/930#issuecomment-491347023

**Comment by plata** [comment]
> Configuration works locally on platinum, but i'm affected by https://github.com/PhoenicisOrg/phoenicis/issues/1925 which i believe is caused by #930 (comment)

This makes no sense. Either the script works as it is or not.

**Comment by Kreyren** [comment]
> > Configuration works locally on platinum, but i'm affected by https://github.com/PhoenicisOrg/phoenicis/issues/1925 which i believe is caused by #930 (comment)
> 
> This makes no sense. Either the script works as it is or not.

it doesn't because the engine is not working on my system -> can't test

**Comment by plata** [comment]
Then we cannot merge this.

**Comment by Kreyren** [comment]
> Then we cannot merge this.

Just to clarify: Blocked by https://github.com/PhoenicisOrg/scripts/issues/930

**Comment by Kreyren** [comment]
> Then we cannot merge this.

Recommending merging under testing flag, once tested we can make release.

**Comment by ImperatorS79** [comment]
@Kreyren Any news about this ?

**Comment by Kreyren** [comment]
> @Kreyren Any news about this ?

Works on my system assuming forcing manuall installation on steam assuming that phoenicis didn't resolve that yet.

**Comment by ImperatorS79** [comment]
> Works on my system assuming forcing manuall installation on steam assuming that phoenicis didn't resolve that yet.

I do not understand what this mean.

**Comment by Kreyren** [comment]
> > Works on my system assuming forcing manuall installation on steam assuming that phoenicis didn't resolve that yet.
> 
> I do not understand what this mean.

- Works on my system
- Last time i checked phoenicis was unable to install **ANY** Steam game -> this is affected.

**Comment by plata** [comment]
Closed until successfully tested from Phoenicis.

**Comment by Kreyren** [comment]
@plata 

> Blocked by #930 for testing

Read the hugging description.. This is phoenicis issue not script issue.

**Pull request closed without merging**
