### PR TITLE
Add UseTakeFocus, Fixes #936, required for #937

### LINKED ISSUE #936: REQUEST: Disable UseTakeFocus on demand
Based on https://github.com/PhoenicisOrg/scripts/issues/934 :

```
Affected by https://bugs.winehq.org/show_bug.cgi?id=45937

Hotfix is to disable UseTakeFocus in HKEY_CURRENT_USER\Software\Wine\X11 Driver\UseTakeFocus with value N
- Hotfix Confirmed
- Fixes game ignoring keyboard input as well
```

Which is confirmed on my setup -> Requesting new verb.

This issue is blocker to https://github.com/PhoenicisOrg/scripts/issues/934

### PR DESCRIPTION
**Pull request by Kreyren**
Add UseTakeFocus, Fixes #936, required for #937 GG

### CODE REVIEW

**Comment by plata** [comment]
Have you tested that #937 works when using this?

**Comment by Kreyren** [comment]
> Have you tested that #937 works when using this?

nope since i'm waiting for engine runtime fix

**Comment by plata** [comment]
@ImperatorS79 small remark: "Fixes #936, required for #937" should not be in the commit title. It's fine in the description.

**Comment by ImperatorS79** [comment]
ok

**Pull request merged**
