### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by plata**
Enjoy!

### CODE REVIEW

**Comment by madoar** [comment]
@plata this PR seems to delete all out translations?

**Comment by plata** [comment]
Crowdin also doesn't show any strings in the translation file. It seems that it cannot read the Messages.properties. I currently have no idea why.

**Comment by plata** [comment]
That's strange: all the lines in the Messages.properties are commented. Why does that happen?

**Comment by plata** [comment]
@madoar this pr should be ok now.

**Pull request merged**
