### PR TITLE
added output to update_translations.py

### PR DESCRIPTION
**Pull request by plata**
This should give us an idea about what's going on in Travis.

### CODE REVIEW

**Comment by plata** [comment]
Doesn't work (at least not easily). I would have to find the last run of the loop.

**Comment by madoar** [comment]
why not add an additional `print "\n"` behind the loop?

**Comment by plata** [comment]
I could do that but where's the difference compared to how it's now?

**Comment by madoar** [comment]
It's easier readable. I also believe that it may be a better idea to print one language in each row.
This is especially a good idea, if we have a lot of supported languages.

**Comment by plata** [comment]
The languages are already printed one per row. You can check the output in Travis.

**Comment by madoar** [comment]
Yes I just saw it.
I guess one or more of the commands you open a subprocess for isn't executed correctly.
Is it possible to force an output for them?

**Comment by plata** [comment]
I tried but it's not really helpful (the pipe is eating all the info). What we could to is split the command and try every portion until we find the issue. But I don't really want to do this on master.

**Comment by plata** [comment]
It must be something with the xgettext. We could see already that the msgmerge and msgcat is working.

**Comment by madoar** [comment]
You could try to setup travis for your fork? (I guess this should work)

**Comment by plata** [comment]
Or just a pull request to play around until it works?

**Comment by madoar** [comment]
Whatever works I guess

**Pull request merged**
