### PR TITLE
Updated fr.po

### PR DESCRIPTION
**Pull request by ImperatorS79**
Need some help for the expression "Sucker monsters into moving into your building" in Unholy heights

### CODE REVIEW

**Comment by plata** [comment]
@qparis can you have a look, please?

**Comment by plata** [comment]
I have updated the .pot on master. Please merge master into your branch and update the missing translations.

**Comment by plata** [comment]
You have to commit the .properties as well, otherwise the translations will not be used.

**Comment by ImperatorS79** [comment]
Ok, wait a minute

**Comment by plata** [comment]
Good. I cannot do the review as I do not know French, so we have to wait until @qparis checks this.

**Comment by madoar** [comment]
I've interpreted the word "sucker" as "lure", i.e.: lure monsters into moving into your building.
In the game you own an apartment building, which you try to rent out to monster tenants. The point is, that different monsters have different preferences. For example there are some ice cube monsters that like it cold, i.e. you should add some cooler equipment to some of your apartments. 
I think that's what your problematic sentence is about.

**Comment by madoar** [comment]
@qparis I think this PR is complete for now, can you please check it? My French is kind of rusty.

**Comment by ImperatorS79** [comment]
I don't understand why there is still conflict...

**Comment by plata** [comment]
@ImperatorS79 can you update the translations in Crowdin directly? You should be able to upload your fr.po there so you don't have to do the work all over again.

**Comment by ImperatorS79** [comment]
@plata I can't, those options are in grey
crowdin

**Comment by plata** [comment]
It's in Settings → Upload Translations. However, I'm not sure if you have the rights to upload it there. Therefore I've uploaded the fr.po from this pull request. Please check if it is correct in Crowdin.

**Comment by ImperatorS79** [comment]
You can use the last one here. I think it's complete.

**Comment by plata** [comment]
I've uploaded the fr.po. As everything should be in Crowdin now, I will close this pull request.

Can you check the remaining French translations in Crowdin (wasn't at 100%)?

**Pull request closed without merging**
