### PR TITLE
Games/OPSU : Initial Commit

### PR DESCRIPTION
**Pull request by Kreyren**
Fixes : https://github.com/PhoenicisOrg/scripts/issues/894

HELP WANTED

Requires sanity check

### CODE REVIEW

**Comment by ImperatorS79** [comment]
opsu! can run natively on linux, according do the homepage, so I will close this.

**Comment by Kreyren** [comment]
> opsu! can run natively on linux, according do the homepage, so I will close this.

How is it relevant?

**Comment by ImperatorS79** [comment]
Why would you want to do a wine script, for a .jar games that you can run natively on linux directly ?
You do not need wine in this case.

**Comment by Kreyren** [comment]
@ImperatorS79 No need to use wine.

Since you need to download dependencies for lots of games that runs natively on linux -> Phoenicis can handle that better expecially when those games doesn't work on deps provided by distro like opsu on fedora that outputs:
```
OpenJDK 64-Bit Server VM warning: You have loaded library /home/jamespark/Games/osu/Natives/liblwjgl.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```

Or other games that needs older version of deps that user don't neccesary want to install.

+ it would expand phoenici's usecase since games would be one click with required deps or methods like decising if you want to play windows version of OSU using WINE or native, etc..

Curent is that if you want to install a game -> you need to debug it.

**Pull request closed without merging**
