### PR TITLE
Add Captvty 3

### PR DESCRIPTION
**Pull request by renard119**

### CODE REVIEW

**Comment by plata** [comment]
Please check the Travis build (it failed because the json format didn't match - run json-align as described in https://phoenicisorg.github.io/scripts/General/tools/ to fix this.

**Comment by Zemogiter** [comment]
I've aligned the .json files but I can't upload them. I remember there was a button left from the "add header text" button that I think would let you upload commits to somebody else's PR but now that option is missing.

**Comment by plata** [comment]
It probably requires write permission on the repository. You should be able to use [insert suggestions](https://help.github.com/articles/incorporating-feedback-in-your-pull-request/).

**Comment by plata** [comment]
@renard119 please fix the Travis build (otherwise we cannot merge this). The json files are not aligned. There's a description in the documentation how to solve that: https://phoenicisorg.github.io/scripts/General/tools/

**Comment by plata** [comment]
Didn't we have this issue before somewhere?

**Comment by qparis** [comment]
> @qparis when trying to download the .zip as a resource, I got a .html instead.

Because the URL is no longer valid: http://releases.captvty.fr/0340f3631221f953f55170d90904318eb662b89b/captvty-3.0.0.63402.zip

**Comment by ImperatorS79** [comment]
http://releases.captvty.fr/8102b289060498841541c50e7ba02efdffd142dd/captvty-3.0.0.63623.zip
http://releases.captvty.fr/c3c442797654587455f15e5b735acad23ba7bb8d/captvty-3.0.0.63623.zip

Ok the url change at any time. Weird.

**Comment by plata** [comment]
Is there maybe another URL redirecting to the correct one?

**Comment by ImperatorS79** [comment]
No update since nearly one year. Feel free to reopen if you can update this.

**Pull request closed without merging**
