### PR TITLE
Clean up translation process + files

### LINKED ISSUE #499: delete .po
Crowdin generates the `.properties` directly. We can delete the `.po` files and remove the `.po` and `.properties` update from `update_translations.py`.

### PR DESCRIPTION
**Pull request by plata**
As Crowdin can generate `.properties` directly from the `.pot`, it is not necessary anymore to update and maintain the `.po` and `.properties` files.

fixes #499

### CODE REVIEW

**Comment by plata** [comment]
We should not push this until we are sure that Crowdin suites our needs.

**Comment by plata** [comment]
I think we can merge this now.

**Comment by madoar** [comment]
Is it possible to extract/generate the affected files from Crowdin later on?

**Comment by plata** [comment]
Not sure if it's possible in Crowdin but there's e.g. [prop2po](https://github.com/translate/translate/blob/de383e74ef7333e0835f2ec3d87480b3c265f3dc/translate/convert/prop2po.py) ([doc](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/prop2po.html)) which could be used for this purpose.

**Comment by madoar** [comment]
I also think we can merge this, but I would like to hear what @qparis thinks about this first

**Comment by plata** [comment]
@madoar we can't really break anything. Even if the tool to convert .properties to .po doesn't work, we can still get the old .po from the git history.

**Pull request merged**
