### PR TITLE
Added Hearthstone

### PR DESCRIPTION
**Pull request by ImperatorS79**
Until BattleNetScript (#212)  is made, this can do the job.

### CODE REVIEW

**Comment by plata** [comment]
@ImperatorS79 don't you want to give #212 a try? It really shouldn't be too difficult. Copy `SteamScript` and change the command which is used to install.

**Comment by ImperatorS79** [comment]
The problem is I don't know how to convert battlenet://{ID} into something wine can understand

**Comment by plata** [comment]
Checkout this: <https://www.reddit.com/r/Overwatch/comments/3qfmms/downloading_the_game_through_the_cmd_prometheus/>

**Comment by ImperatorS79** [comment]
Need to find the right name for Hearthstone

**Comment by plata** [comment]
Ok. I'll merge this now. If #212 works, you can update it later.

**Pull request merged**
