### PR TITLE
Added Dragon Ball Xenoverse

### PR DESCRIPTION
**Pull request by ImperatorS79**
Testing because I do not own the game.

### CODE REVIEW

**Comment by plata** [comment]
As you couldn't test the game: can you provide some evidence that it should run with that configuration (e.g. AppDB)?

**Comment by ImperatorS79** [comment]
Platinum in appDB -> [https://appdb.winehq.org/objectManager.php?sClass=version&iId=31818](https://appdb.winehq.org/objectManager.php?sClass=version&iId=31818)

Wine-staging for steam

**Comment by plata** [comment]
Shouldn't this work on Wine stable as well?

**Comment by ImperatorS79** [comment]
I thought Steam worked only under recent wine staging version.

**Comment by plata** [comment]
I think it should work. Can you try? We should prefer stable to staging/devel if possible.

**Comment by ImperatorS79** [comment]
Ok, good to know.

**Pull request merged**
