### PR TITLE
Documentation : rework

### PR DESCRIPTION
**Pull request by Kreyren**
Relevant : https://github.com/PhoenicisOrg/scripts/issues/799

Created a concept of new documentation for readme and contribution.

My abstract is to make `CONTRIBUTION.md` file will full instructions about contribution to a repository.

README.md should have summary of this file and introduction.

Recommends renaming PhoenicisOrg/scripts -> PhoenicisOrg/installers -- Reason is that <USER>/script is widely used for a user scripts on github which may create conflicts. 

Will add images to make the documentation effective to read. 

Should follow up with https://github.com/PhoenicisOrg/scripts/issues/799#issuecomment-453222939

## Looking for feedback

### CODE REVIEW

**Comment by Kreyren** [comment]
omg.. removing dishonored 2 from documentation branch.. I had to fix my scripts.

**Comment by Kreyren** [comment]
I made it worse, will re-push

**Comment by Kreyren** [comment]
Requesting removal of #810, reason spam.

**Comment by qparis** [comment]
Try to remove your fork and work from a clean tree.
Backup your files if necessary because all your MR will be closed

**Comment by Kreyren** [comment]
@qparis It's fixed now i had corrupted `git` on local system sorry about it >.> 

Clean MR are already up

**Pull request closed without merging**
