### PR TITLE
Add "Automatic Rebase" GitHub action

### PR DESCRIPTION
**Pull request by plata**
see https://github.com/marketplace/actions/automatic-rebase

### CODE REVIEW

**Comment by madoar** [comment]
Would this GitHub action work for us (because of: https://github.com/cirrus-actions/rebase/issues/12)?

**Comment by plata** [comment]
Mh. Didn't see that.

**Comment by madoar** [comment]
@plata how should we continue with this PR?

**Comment by plata** [comment]
Doesn't seem like there will be a solution anytime soon so we can as well close this.

**Pull request closed without merging**
