### PR TITLE
Add Totally Accurate Battlegrounds

### PR DESCRIPTION
**Pull request by plata**
runs but performance could be better

### CODE REVIEW

**Comment by Zemogiter** [comment]
Have you tried Vulkan?

**Comment by plata** [comment]
No. How would I do that?

**Comment by Zemogiter** [comment]
Use dxvk verb.

**Comment by plata** [comment]
Just using the verb will not make the game run in Vulkan, will it?

**Comment by ImperatorS79** [comment]
Pol version of wine does not support vulkan atm, so impossible to test.
[DXVK](https://github.com/doitsujin/dxvk) is a "translation layer" from d3d11 to vulkan. The verbs install 2 ddl's (d3d11 and dxgi) inside wine windows directory and set an override. A lot of players actually use it to have better performance in comparaison to wine opengl to d3d11 (just check youtube to see ;-) ).
But Totally Accurate Battlegrounds use DirectX 9, so the corresponding project is [VK9](https://github.com/disks86/VK9).

**Comment by plata** [comment]
I don't think it's a good idea to use vulkan for this then. Maybe TABS will get some optimization to run better.

**Pull request merged**
