### PR TITLE
Games/Hearthstone: Nativestone from FOSSzard Entertainment

### PR DESCRIPTION
**Pull request by Kreyren**
Fixes: https://github.com/PhoenicisOrg/scripts/issues/924

### CODE REVIEW

**Comment by plata** [comment]
From what I can tell, the script has no functionality at all. It is not helpful for anybody to open a pull request like this. Of course, you are welcome to ask if you hit some problem while creating a script but this is basically an empty template plus some comments.

**Comment by Kreyren** [comment]
@plata i know let me finish the thing then i move it from draft

**Comment by qparis** [comment]
Agreed with @plata and already expressed this point of view before

**Comment by Kreyren** [comment]
i'm aware, but this is custom script so it will probably need some includes and this way it makes it easier to track and for me to work on it. -> Ignore untill proposed.

**Comment by qparis** [comment]
> i'm aware, but this is custom script so it will probably need some includes and this way it makes it easier to track and for me to work on it. -> Ignore untill proposed.

Then, please reopen the merge request once you are ready to propose something. Everything will be tracked

**Comment by Kreyren** [comment]
:man_facepalming: i will just update the commit, reopen after then

**Comment by qparis** [comment]
Yes. Imagine every contributor opens merge request and issues and say « ignore this for now ». This makes tasks hard to prioritize is not helping us at all.

**Comment by Kreyren** [comment]
@qparis Seems perfectly sane.. that's what drafts are for so that contributors could cooperate on the features.

**Pull request closed without merging**
