### PR TITLE
Add MinionMasters

### PR DESCRIPTION
**Pull request by Kreyren**
DISCLAIMER: `main.png` is responsibility of phoenicis developers where it's beeing used under fair use.

Affected by https://github.com/PhoenicisOrg/scripts/issues/881#event-2391939521 -> Can not test.

Fixes: https://github.com/PhoenicisOrg/scripts/issues/957

Should work, bcs i don't do mistakes :p 

DO NOT MERGE! Not tested!

### CODE REVIEW

**Comment by Kreyren** [comment]
`main.png` is missing and it won't be contributed by me cause of https://github.com/PhoenicisOrg/phoenicis/issues/1943

**Comment by plata** [comment]
Both scripts are working? Does it make sense to provide a separate version for DXV9? I think that it might be confusing for the average user.

**Comment by Kreyren** [comment]
> Both scripts are working? Does it make sense to provide a separate version for DXV9? I think that it might be confusing for the average user.

i'm not sure how DXV9 works so untill it's confirmed to be reliable i'm providing both options with preference on non-DXV9 once confirmed i will prefer DXV9 but still support other configurations.

**Comment by plata** [comment]
@ImperatorS79 what do you think about this?

**Comment by ImperatorS79** [comment]
I wonder if it should not be better to simply ask in the D9VK and DXVK verbs if the user wants to install it or not. The best would be to test vulkan support to do the decision (as DXVK brings **more** performance than wine3d)

There is a problem with jmimemagic currently preventing phoenicis to untar any .tar (see #932).

**Comment by plata** [comment]
In any case, I think we should have an automatic way because many users will not know what DXVK is. Maybe the best solution for now is using only the script without DXV9. What do you think?

> There is a problem with jmimemagic currently preventing phoenicis to untar any .tar (see #932).

Does this mean that this script cannot work at all currently (including that it must be untested)?

**Comment by ImperatorS79** [comment]
For any reasons, all script "untaring" things have started to not work :/.

**Comment by plata** [comment]
Like stated before, we cannot have untested pull requests (or at least in draft if support is required). Therefore I close this until it is tested.

**Comment by Kreyren** [comment]
@plata works on my end, but blocked https://github.com/PhoenicisOrg/scripts/issues/959

open the MR omg

**Comment by plata** [comment]
Sorry but this is impossible. You're telling me that you cannot install any Steam app but have tested a Steam app at the same time?

**Comment by Kreyren** [comment]
@plata *phoenicis can't install any steam apps..

 i installed it manually once phoenicis launched steam to test it. There are however some issue with steam that i'm investigating now and game has graphical glitches that are reproducable on random which i believe are caused either by my GPU configuration or DXVK.

**Comment by Kreyren** [comment]
@plata https://i.imgur.com/S8S6EJY.jpg

**Pull request closed without merging**
