### PR TITLE
Revert latest wine version to 4.0 and 4.7

### PR DESCRIPTION
**Pull request by ImperatorS79**
Others have not been build yet @qparis

### CODE REVIEW

**Comment by plata** [comment]
Can you open PRs to update the versions again as soon as they are built?

**Comment by qparis** [comment]
I don't understand, it seems that they are built: https://www.playonlinux.com/wine/binaries/phoenicis/upstream-linux-amd64/

**Comment by ImperatorS79** [comment]
Well, for staging at least 4.8 was crashing my scripts, while 4.7 was working. Maybe I was a little bit too fast when merging this.

**Comment by qparis** [comment]
I think staging and upstream version should be put in seperable variables

**Comment by ImperatorS79** [comment]
They are, it just me that modified them at once ^^.

**Pull request merged**
