### PR TITLE
Update Subnautica: fix mixed tabs and spaces indentation

### LINKED ISSUE #522: fix Subnautica format
@Zemogiter 

see https://app.codacy.com/app/PhoenicisOrg/Scripts/file/15735585878/issues/source?bid=6547561&fileBranchId=6547561#l21

### PR DESCRIPTION
**Pull request by Zemogiter**
fixes #522

### CODE REVIEW

**Comment by plata** [comment]
What's the purpose of this pull request?

**Comment by Zemogiter** [comment]
#522

**Comment by plata** [comment]
Please follow these steps:
1. merge the up-to-date master
2. check in Codacy if the pull request fixes the issue
3. use a meaningful title for the pull request (follow guidelines in README)
4. add "fixes #522" to the description to close the issue once the pull request is merged

**Comment by Zemogiter** [comment]
Ready for review.

**Pull request merged**
