### PR TITLE
Games/RocketLeague : Initial Commit

### PR DESCRIPTION
**Pull request by Kreyren**
### Abstract

Make Rocket League work on WINE.

Export shaders to prevent freezes if Psyonic won't fix em.

Make game rescale on whole fullscreen if different resolution is used.

If DirectX 9 is used make it work on DXVK.

Click play -> Opens a game.

### Reasoning

Game has native support which seems to be WINE wrapped.
- Has freezes if player enters/interact with new object -> Shader issue?
- Is unable to scale on fullscreen if smaller resolution is used.
- Could benefit from DXVK wrapped in dgvoodoo2
- Upstream only supports SteamOS -> probably more issues to come on linux due upstream's incompetence.

Linux support is not provided, Rocket League for linux is in BETA. -> Rocket League for Linux is garbage.
image

### Research

Wine wrapped windows app?

https://appdb.winehq.org/objectManager.php?sClass=version&iId=32371 -> Seems to work ootb.

Steam is able to force windows version for proton on native linux. https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1703951108827819236

Relevant: https://github.com/ValveSoftware/Proton/issues/102

Seems to work with no problem on proton `3.16-7 Beta`, Shaders needs to be preloaded.

---

Signed-off-by: Jacob Hrbek <werifGX@gmail.com>

### CODE REVIEW

**Comment by qparis** [comment]
Please ... do not send empty merge request. It just adds confusion

**Comment by Kreyren** [comment]
> Please ... do not send empty merge request. It just adds confusion

It's not merge request it's draft..

**Comment by qparis** [comment]
It is still a merge request

**Comment by Kreyren** [comment]
@qparis 

Refferenced on https://github.com/PhoenicisOrg/phoenicis/issues/1850#issuecomment-466101534

i made this draft.. Since this allows more effective script development?

**Comment by qparis** [comment]
I agree that draft should be used when the PR is not ready. However, there are no PR at all here since you have not written any code. I suggest not to do it because it drowns other legitimate merge request that need reviews

**Comment by Kreyren** [comment]
@qparis well i'm doing my best and you can't make a script without research which i want to provide in this draft followed by whatever configuration i can do.. Note that research takes time too. it's like 2 days for one game at minimum..

I can make a script that downloads source, fills requested values for variables and installs required dependencies. 
- I've noticed that i do some syntax errors, but there is no QA for me to check them without knowing phoenicis's source afaik.

Rest like making gallium9, dgvoodoo2, etc.. should be done by phoenicis

Or how else do you want scripts to be developed?

**Comment by qparis** [comment]
No problem to use draft to discuss. However, there are no question and no code here.  This looks like a feature request and not a merge request. Please just wait the moment when you have something to show before opening a merge request

**Comment by Kreyren** [comment]
@qparis it's just research for now.. code will be added once game is tested and data is provided so that we know what works and what doesnt to make the script.

Should be encouraged in draft in case others want to provide relevant data to research since research takes time too.. 

> Please just wait the moment when you have something to show before opening a merge request

some data are already provided with reasoning and suspected issue, dependencies and practicall tests will follow.

**Comment by Zemogiter** [comment]
This game have a native linux client.

**Comment by Kreyren** [comment]
> This game have a native linux client.

Which seems to be wrapped in WINE and has freezes which i suspect are caused by shaders + in theory we can make DXVK work on it.

**Comment by Zemogiter** [comment]
There are no subcategories in `Games`.

**Comment by Kreyren** [comment]
> There are no subcategories in `Games`.

Noted, also should be o.o

**Comment by plata** [comment]
@Kreyren it's a game. There's no sense in putting it somewhere else.

**Comment by Kreyren** [comment]
@plata Why is it sane to spam phoenicis with one big category full of games? Games has categories and those can be used for the end-user to chose what he wants to play alike:

I want to play esport games -> Choose esport category and choose games that are relevant.

**Comment by madoar** [comment]
I like the idea to add application subcategories. There are two questions we need to answer in my opinion:
- how do application subcategories need to be modeled inside the script repository?
- how should they be shown visually? 

Regardless this should be discussed in its own issue. @Kreyren can you please create a new issue for this?

**Comment by plata** [comment]
Don't want to extend the discussion here (like @madoar said, this should be a separate issue). However, my main concern is that it should be obvious in which category an application is located.

**Comment by plata** [comment]
Closed due to inactivity. Feel free to reopen if the app works.

**Pull request closed without merging**
