### PR TITLE
Fix font antialasing issue on OSX 

### PR DESCRIPTION
**Pull request by qparis**
With:
capture d ecran 2018-10-17 a 00 07 06

Without:
capture d ecran 2018-10-17 a 00 09 01

### CODE REVIEW

**Comment by plata** [comment]
Please check Codacy.

**Comment by madoar** [comment]
Unrelated to the content of this PR:
When looking at the file changes, I see that the `operatingSystemFetcher` object contains a method named `fetchCurrentOperationSystem()`.
I think the method name contains a spelling error and should be changed to `fetchCurrentOperatingSystem()`.
Should I open a new issue in the phoenicis repository for the name change?

**Comment by plata** [comment]
Yes, open a new issue.

**Comment by madoar** [comment]
Ok, I've just created the issue https://github.com/PhoenicisOrg/phoenicis/issues/1428

**Pull request merged**
