### PR TITLE
Use Java.type to access Java classes

### PR DESCRIPTION
**Pull request by plata**
see [Graal JavaScript to Java interoperability](https://github.com/graalvm/graaljs/blob/master/docs/user/JavaInterop.md)

### CODE REVIEW

**Comment by plata** [comment]
That's a different topic. This PR doesn't really change anything. It only ensures that what we have currently works with Nashorn and Graal.

**Comment by madoar** [comment]
Oh, I thought the filesystem module was usable with nashorn... 
Sorry about that

**Comment by plata** [comment]
Now I'm confused.

**Comment by madoar** [comment]
You don't need to be. I thought nashorn would support the filesystem module of JS, but this isn't the case because it doesn't seem to support the `require` command. Therefore my whole point is moot.

If we could use the filesystem module it would be the more clean solution with regards to https://github.com/PhoenicisOrg/phoenicis/issues/1630.

**Comment by plata** [comment]
Understood.

**Pull request merged**
