### PR TITLE
Introduce the Module System to the Verbs

### LINKED ISSUE #1082: Undefined "filesToExtract" in Xact Script
I'm currently refactoring parts of the verbs and discovered a possible error in the `xact`script.

In the following line I believe `filesToExtract` to be unset/undefined:

https://github.com/PhoenicisOrg/scripts/blob/79537f88aecf4bbeb867fe0d22c5580bded786b9/Engines/Wine/Verbs/xact/script.js#L38

@plata @ImperatorS79 what do you think?

### PR DESCRIPTION
**Pull request by madoar**
This PR introduces the module system to the verbs (see #1080)

Fixes #1082

### CODE REVIEW

**Comment by plata** [comment]
Please update the documentation (e.g. https://github.com/PhoenicisOrg/scripts/blob/master/docs/_docs/Develop/script-js.md#prepost-install-hooks).

**Comment by madoar** [comment]
@plata done in c1ca9b1

**Comment by madoar** [comment]
@plata done

**Comment by ImperatorS79** [comment]
Can this be merged now ?

**Pull request merged**
