### PR TITLE
Add Assassin's Creed: Rogue

### PR DESCRIPTION
**Pull request by Kreyren**
Credit: https://github.com/Haoose/UPLAY_GAME_ID/blob/master/README.md

Blocked by: https://github.com/PhoenicisOrg/scripts/pull/978

### CODE REVIEW

**Comment by qparis** [comment]
Does the game run?

**Comment by Kreyren** [comment]
> Does the game run?

> Blocked by: #978

**Comment by qparis** [comment]
You can still test it locally

**Comment by Kreyren** [comment]
> You can still test it locally

Nope since i need to make it work on your runtime and s!@#$ -> required to run on phoenicis, local tests are irelevant otherwise league of legends would work on phoenicis..

**Pull request closed without merging**
