### PR TITLE
Games/LeagueOflegends : Update script.json

### PR DESCRIPTION
**Pull request by Kreyren**
League Of Legends in phoenicis is outdated and not working, set it in testing untill #841 is fixed for #797 to be merged and to avoid issues alike #870

### CODE REVIEW

**Comment by ImperatorS79** [comment]
Check json format with json-align as stated in the wiki

**Comment by Kreyren** [comment]
> Check json format with json-align as stated in the wiki.

Formating with json-align.

**Comment by Kreyren** [comment]
omg DO NOT MERGE! made a terrible mistake

**Comment by Kreyren** [comment]
Squashed, sorry for commit spam

**Comment by Zemogiter** [comment]
Why this isn't included in #797 ?

**Comment by ImperatorS79** [comment]
The script is not working at all on master so it is normal that @Kreyren wanted to change the testing status.

**Pull request merged**
